### ISSUE TITLE
Post geojson file

### ISSUE THREAD

**Issue by samistat08** [perliedman/elevation-service#15]
How can I post a Geojson file to your repo and get back file with elevation?

**Comment by perliedman** [comment]
You can make a `POST` request to https://data.cykelbanor.se/elevation/geojson with GeoJSON as the request's body, and you'll get the result with elevations back in the response.

Be adviced this is a _demo_ service, and I take no kind of responsibility that this service will always be up, and it might disappear without notice at any point.
